import { IAsset } from "./Asset";
import { IAssetAmount } from "./AssetAmount";
import { IAmount } from "./Amount";
export declare type Pool = ReturnType<typeof Pool>;
export declare type IPool = Omit<Pool, "poolUnits" | "calculatePoolUnits">;
export declare function Pool(a: IAssetAmount, b: IAssetAmount, poolUnits?: IAmount): {
    amounts: [IAssetAmount, IAssetAmount];
    readonly externalAmount: IAssetAmount | undefined;
    readonly nativeAmount: IAssetAmount | undefined;
    otherAsset: (asset: IAsset) => IAssetAmount;
    symbol: () => string;
    contains: (...assets: IAsset[]) => boolean;
    toString: () => string;
    getAmount: (asset: string | IAsset) => IAssetAmount;
    poolUnits: IAmount;
    priceAsset(asset: IAsset): IAssetAmount;
    calcProviderFee(x: IAssetAmount): IAssetAmount;
    calcPriceImpact(x: IAssetAmount): IAmount;
    calcSwapResult(x: IAssetAmount): IAssetAmount;
    calcReverseSwapResult(Sa: IAssetAmount): IAssetAmount;
    calculatePoolUnits(nativeAssetAmount: IAssetAmount, externalAssetAmount: IAssetAmount): IAmount[];
};
export declare function CompositePool(pair1: IPool, pair2: IPool): IPool;
